# Generated by Django 4.2.5 on 2023-09-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RANGO', '0003_remove_register_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='landnmark',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='locality',
            new_name='Username',
        ),
    ]
