# Generated by Django 4.2.5 on 2023-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RANGO', '0005_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurantname', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=100)),
                ('Pasword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
    ]
