# Generated by Django 4.2.5 on 2023-09-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RANGO', '0006_login_remove_register_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
