# Generated by Django 4.2.5 on 2023-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RANGO', '0007_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurantname', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
