# Generated by Django 4.2.5 on 2023-10-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RANGO', '0008_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Login_details',
        ),
    ]
